apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plio
  namespace: plio
spec:
  secretName: plio
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
  dnsNames:
    - api.runplio.com
  issuerRef:
    name: letsencrypt-prod-cluster
    kind: ClusterIssuer
    group: cert-manager.io
