apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: plio
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: plio
    hosts:
    - "api.runplio.com"
