resources:
- ./../base
nameSuffix: -demo
transformers:
  - |-
    apiVersion: builtin
    kind: NamespaceTransformer
    metadata:
      name: unused
      namespace: plio-demo
    unsetOnly: true
patches:
- patch: |-
    - op: replace
      path: /spec/gateways
      value:
      - plio-demo/plio-demo
  target:
    kind: VirtualService
- patch: |-
    - op: replace
      path: /spec/http/0/route/0/destination/host
      value: plio-demo.plio-demo.svc.cluster.local
  target:
    kind: VirtualService
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
