openapi: 3.1.0
info:
  description: Check for AWS infra compliance with SOC2
  title: Plio
  version: v0.0.1
servers:
- url: https://api.runplio.com
paths:
  /integrations:
    get:
      description: Get all integrations
      operationId: GetIntegrations
      responses:
        "200":
          content:
            application/json:
              examples:
                example-1:
                  value:
                  - name: AWS
              schema:
                items:
                  $ref: '#/components/schemas/Integration'
                type: array
          description: Successful response
  /integrations/aws:
    post:
      description: Run AWS integration
      operationId: RunAWSIntegration
      responses:
        "200":
          content:
            application/json:
              examples:
                example-1:
                  value:
                    info: IAM check completed successfully
                    status: ok
              schema:
                $ref: '#/components/schemas/AWSIntegrationResponse'
          description: Successful operation
components:
  schemas:
    Integration:
      example:
        name: name
      properties:
        name:
          type: string
    AWSIntegrationResponse:
      example:
        info: info
        status: status
      properties:
        info:
          type: string
        status:
          type: string
