name: Docker Image CI

on:
  push:
    branches: [ "main" ]
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::666190772232:role/PlioGithubActions
        role-session-name: plio-build
        aws-region: us-east-1
    - id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    - env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        REPOSITORY: plio
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build . -f server/Dockerfile -t $REGISTRY/$REPOSITORY:$IMAGE_TAG
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::666190772232:role/PlioGithubActions
        role-session-name: plio-deploy
        aws-region: us-east-1
    - run: aws eks update-kubeconfig --name app-server --region us-east-1
    - run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh"  | bash
        cd server/infra/demo && kustomize edit set image plio=666190772232.dkr.ecr.us-east-1.amazonaws.com/plio:${{ github.sha }}
        kubectl apply -k server/infra/demo && kubectl rollout restart deployment plio-demo -n plio-demo
